[WIP]サーバーサイド：購入機能の実装
Chestnut-07/fleamarket_sample_kagawa-b pull request #14
Opened 2021-02-09 09:16 UTC by bonkura-bird

# what
クレジットカードの登録機能、出品した商品を購入する機能を実装する。
使用技術：payjp
# why
ユーザー間の取引成立のために必要な機能であるため。

2021-02-13 10:06 UTC, bonkura-bird commented
カード削除
![カード削除](https://user-images.githubusercontent.com/74849580/107847398-80991880-6e2e-11eb-842a-a20b730d3783.gif)

2021-02-13 10:19 UTC, bonkura-bird commented
カード登録
![カード削除](https://user-images.githubusercontent.com/74849580/107847606-619b8600-6e30-11eb-8f5d-560a1bfabc2e.gif)

2021-02-13 10:22 UTC, bonkura-bird commented
無効なカードの登録
![カード登録失敗](https://user-images.githubusercontent.com/74849580/107847671-d79fed00-6e30-11eb-88cd-c756b2cfeef5.gif)

2021-02-13 10:24 UTC, bonkura-bird commented
カード登録
![カード登録](https://user-images.githubusercontent.com/74849580/107847707-16ce3e00-6e31-11eb-83ed-9864b6f43434.gif)

2021-02-13 10:56 UTC, bonkura-bird commented
<img width="1271" alt="スクリーンショット 2021-02-13 19 50 59" src="https://user-images.githubusercontent.com/74849580/107848284-79293d80-6e35-11eb-9d7c-e7b1972f68b4.png">
商品購入
![商品購入](https://user-images.githubusercontent.com/74849580/107848269-5d259c00-6e35-11eb-8697-5994fbd99871.gif)
<img width="1278" alt="スクリーンショット 2021-02-13 19 41 28" src="https://user-images.githubusercontent.com/74849580/107848277-70d10280-6e35-11eb-89f7-b4ce1976d1b1.png">

2021-02-13 10:57 UTC, bonkura-bird commented
商品購入

2021-02-13 10:59 UTC, bonkura-bird commented
商品DB＆Payjpコンソール
<img width="1278" alt="スクリーンショット 2021-02-13 19 41 28" src="https://user-images.githubusercontent.com/74849580/107848322-e50ba600-6e35-11eb-81d4-99a0bfac5ee2.png">
<img width="1271" alt="スクリーンショット 2021-02-13 19 50 59" src="https://user-images.githubusercontent.com/74849580/107848332-ec32b400-6e35-11eb-9f54-e7c313925da4.png">
<img width="1084" alt="スクリーンショット 2021-02-13 19 50 45" src="https://user-images.githubusercontent.com/74849580/107848336-f48aef00-6e35-11eb-8a56-32d012998ab0.png">

2021-02-13 13:20 UTC, Chestnut-07 reviewed
レビュー依頼ありがとうございます。
１点気になる点があったため、コメントさせていただきました。

2021-02-13 13:20 UTC, Chestnut-07 commented on app/controllers/items_controller.rb
> +    end
何箇所かありますが、elseの記述のみであるならば、ifではなくunlessでも良いと思います。

2021-02-13 15:00 UTC, bonkura-bird commented on app/controllers/items_controller.rb
> +    end
unlessに変更しました。

2021-02-14 00:48 UTC, Chestnut-07 commented
LGTMです

2021-02-14 01:56 UTC, yupimaru requested changes
レビュー依頼ありがとうございます！
コメントしましたので、ご確認をお願いいたします！

2021-02-14 01:56 UTC, yupimaru commented on app/controllers/items_controller.rb
> +    @item = Item.find(params[:id])
```ruby
@item = Item.find(params[:id])
```

上記記述ですが、複数のアクションで使用しているようですので、
`private`以下にメソッドとして切り分けましょう。

2021-02-14 01:56 UTC, yupimaru commented on app/controllers/items_controller.rb
> +  def purchase_confirmation
以下の状態である場合、購入確認画面及び購入ができると好ましくないかと思いますがいかがでしょうか？

```
- ユーザーがログイン状態にないとき
- 該当の商品の出品者とログインユーザーが同一であるとき
- 該当の商品が既に売り切れているとき
```

2021-02-14 01:56 UTC, yupimaru commented on app/controllers/items_controller.rb
> +    @card = CreditCard.where(user_id: current_user.id).first
```ruby
@card = CreditCard.where(user_id: current_user.id).first
```

上記記述ですが、複数のアクションで使用しているようですので、
`private`以下にメソッドとして切り分けましょう。

2021-02-14 01:56 UTC, yupimaru commented on app/controllers/users_controller.rb
> +    @user = current_user
```ruby
@user = current_user
```

未ログイン状態である場合エラーになりそうですが、挙動としては問題有りませんか？

2021-02-14 01:56 UTC, yupimaru commented on app/controllers/credit_cards_controller.rb
> +  def create
以下の状態である場合、カード登録は出来ないようにエラーハンドリングしたほうが良いかと思いますがいかがでしょうか？

```
- ユーザーが未ログイン状態である場合
```

2021-02-14 04:02 UTC, bonkura-bird commented on app/controllers/items_controller.rb
> +    @item = Item.find(params[:id])
privateでメソッド化しました。

2021-02-14 04:09 UTC, bonkura-bird commented on app/controllers/items_controller.rb
> +    @card = CreditCard.where(user_id: current_user.id).first
privateでメソッド化しました。

2021-02-14 04:33 UTC, bonkura-bird commented on app/controllers/items_controller.rb
> +  def purchase_confirmation
条件分岐を追加しました。

2021-02-14 04:35 UTC, bonkura-bird commented on app/controllers/users_controller.rb
> +    @user = current_user
ログイン状態による条件分岐を追加しました。

2021-02-14 04:40 UTC, bonkura-bird commented on app/controllers/credit_cards_controller.rb
> +  def create
ログイン状態による分岐を追加しました。

2021-02-14 04:45 UTC, syuji-yamamoto commented
レビュー依頼ありがとうございます！
こちらのプルリクエストにて、コンフリクトが起きていますので、まずはこちらを解消しましょう！
githubのブラウザエディタでコンフリクトを解消できますので、「Resolve conflicts」をクリックして解消しましょう。
その後、再度レビュー依頼フォームにてご提出をお願いします。

2021-02-14 05:58 UTC, bonkura-bird commented
すいません。見落としていました。
コンフリクト解消しました。

2021-02-14 06:28 UTC, goku-naoki commented
レビュー依頼ありがとございます！
ユーザーのログイン制約に関してコメントさせて頂いたのご確認お願い致します。

2021-02-14 06:28 UTC, goku-naoki commented on app/controllers/items_controller.rb
> +    if !user_signed_in?
deviseのauthenticate_user!を使用する事で、ログインの制約を掛けられるので使用しましょう。
itmesコントローラでログインの制約を掛けることが多いため、便利かと思います。

2021-02-14 06:28 UTC, goku-naoki commented on app/controllers/users_controller.rb
> +      redirect_to root_path, alert: "ログインしてください。"
authenticate_user!を使用していきましょう。

2021-02-14 06:40 UTC, bonkura-bird commented on app/controllers/items_controller.rb
> +    if !user_signed_in?
authenticate_user!に修正しました。

2021-02-14 06:40 UTC, bonkura-bird commented on app/controllers/users_controller.rb
> +      redirect_to root_path, alert: "ログインしてください。"
authenticate_user!に修正しました。

2021-02-14 06:46 UTC, goku-naoki commented
修正ありがとうございます！
LGTMとさせて頂きます！
お疲れ様です！

2021-02-14 06:50 UTC, merged