[WIP]マークアップ：マイページ
Chestnut-07/fleamarket_sample_kagawa-b pull request #3
Opened 2021-01-20 03:53 UTC by bonkura-bird

# What
フリマサイトのマイページを作成

マークアップ / Haml
クラス設計 / BEM
スタイリング / Sass
# Why
本アプリの機能を使用するために必須の画面であるため

2021-01-30 08:10 UTC, bonkura-bird commented
view:マイページ
![localhost_3000_users_id](https://user-images.githubusercontent.com/74849580/106351187-09d42980-631e-11eb-9920-b6f73175a9c4.png)

2021-01-30 08:11 UTC, bonkura-bird commented
view:支払い方法
![localhost_3000_users_id (1)](https://user-images.githubusercontent.com/74849580/106351193-1eb0bd00-631e-11eb-8b2a-37beb1f92f7b.png)

2021-01-30 08:11 UTC, bonkura-bird commented
view:クレジットカード登録フォーム
![localhost_3000_users_id (1)](https://user-images.githubusercontent.com/74849580/106351202-2ff9c980-631e-11eb-8c78-dbf29d28b358.png)

2021-01-30 08:41 UTC, Chestnut-07 reviewed
レビュー依頼ありがとうございます。
コンフリクトが発生しているので、そこの修正をお願いします。
もし、修正後でもビューが変わらない様であれば、LGTMです。

2021-01-31 04:39 UTC, bonkura-bird commented
@Chestnut-07 
コンフリクトの解消、ビューの調整、ともに完了しました。

2021-01-31 06:45 UTC, Chestnut-07 commented
LGTMです。

2021-01-31 07:02 UTC, goku-naoki reviewed
レビュー依頼ありがとうございます！
SCSSも変数が適切に使えており、素晴らしいですね。
一点、不要なコメントアウトに関してコメント致しましたのでご確認お願い致します。

2021-01-31 07:02 UTC, goku-naoki commented on app/views/users/_top_header.html.haml
> +        = form_with url:'#', class: "SearchForm__form", method: :get, local: true do |f|
不要なコメントアウトは削除しておきましょう。

2021-01-31 09:27 UTC, bonkura-bird commented on app/views/users/_top_header.html.haml
> +        = form_with url:'#', class: "SearchForm__form", method: :get, local: true do |f|
不要なコメントアウトを削除しました。

2021-02-02 04:09 UTC, yupimaru requested changes
レビュー依頼ありがとうございます。
修正点確認させて頂きました。

追加でコメントしておりますので、ご確認のほどよろしくお願いいたします。

2021-02-02 04:09 UTC, yupimaru commented on app/assets/stylesheets/modules/credit_cards_new.scss
> +$str-line-height: 140%;
```SCSS
$border-color: #efefef;
$view-background-color: whitesmoke;
$str-line-height: 140%;
```

変数化の記述は、ファイルを切り分けましょう。
今の記述ですと、今後メンテナンス時にどこで何を変数化しているのかわからなくなります。

2021-02-02 04:09 UTC, yupimaru commented on app/assets/stylesheets/modules/credit_cards_show.scss
> +@import "advertising_&_footer";
```SCSS
@import "top_header";
@import "side_bar_&_main_body";
@import "advertising_&_footer";
```

上記記述はこちらのファイルに必要ですか？

2021-02-02 04:09 UTC, yupimaru commented on app/assets/stylesheets/modules/users_show.scss
> +}
```SCSS
@import "top_header";
@import "side_bar_&_main_body";
@import "advertising_&_footer";
* {
  box-sizing: border-box;
}
a {
  text-decoration: none;
  color: #0099e8;
}
body {
  font-family: 'Source Sans Pro', Helvetica , Arial, '游ゴシック体', 'YuGothic', 'メイリオ', 'Meiryo', sans-serif;
  background-color: #f5f5f5;
}
```

上記記述はこちらのファイルに必要ですか？

2021-02-02 04:09 UTC, yupimaru commented on app/views/credit_cards/new.html.haml
> +            = f.select :exp_month, [["1", "1"], ["2", "2"], ["3", "3"], ["4", "4"], ["5", "5"], ["6", "6"], ["7", "7"], ["8", "8"], ["9", "9"], ["10", "10"], ["11", "11"], ["12", "12"]], { include_bl
```haml
= f.select :exp_month, [["1", "1"], ["2", "2"], ["3", "3"], ["4", "4"], ["5", "5"], ["6", "6"], ["7", "7"], ["8", "8"], ["9", "9"], ["10", "10"], ["11", "11"], ["12", "12"]], { include_blank: "---" }, { id: "exp_month_form", class: "ExpDate", required: true }
```

もう少しコンパクトに記述してみましょう。

2021-02-02 04:09 UTC, yupimaru commented on app/views/credit_cards/new.html.haml
> +            = f.select :exp_year, [["21", "21"], ["22", "22"], ["23", "23"], ["24", "24"], ["25", "25"], ["26", "26"], ["27", "27"], ["28", "28"], ["29", "29"], ["30", "30"], ["31", "31"]], { include
```haml
= f.select :exp_year, [["21", "21"], ["22", "22"], ["23", "23"], ["24", "24"], ["25", "25"], ["26", "26"], ["27", "27"], ["28", "28"], ["29", "29"], ["30", "30"], ["31", "31"]], { include_blank: "---" }, { id: "exp_year_form", class: "ExpDate", required: true }
```

もう少しコンパクトに記述してみましょう。

2021-02-02 05:56 UTC, bonkura-bird commented on app/assets/stylesheets/modules/credit_cards_new.scss
> +$str-line-height: 140%;
変数をまとめるファイルを作成しました。_variables.scss

2021-02-02 05:56 UTC, bonkura-bird commented on app/assets/stylesheets/modules/credit_cards_show.scss
> +@import "advertising_&_footer";
application.scssに移行しました。

2021-02-02 05:58 UTC, bonkura-bird commented on app/assets/stylesheets/modules/users_show.scss
> +}
@impotは削除しました。
_base.scssを作成し、スタイルの設定を移行しました。

2021-02-02 06:35 UTC, bonkura-bird commented on app/views/credit_cards/new.html.haml
> +            = f.select :exp_month, [["1", "1"], ["2", "2"], ["3", "3"], ["4", "4"], ["5", "5"], ["6", "6"], ["7", "7"], ["8", "8"], ["9", "9"], ["10", "10"], ["11", "11"], ["12", "12"]], { include_bl
選択肢を配列形式に変更しました。

2021-02-02 06:56 UTC, bonkura-bird commented on app/views/credit_cards/new.html.haml
> +            = f.select :exp_year, [["21", "21"], ["22", "22"], ["23", "23"], ["24", "24"], ["25", "25"], ["26", "26"], ["27", "27"], ["28", "28"], ["29", "29"], ["30", "30"], ["31", "31"]], { include
コントローラに今日以降の１０年間を格納した配列を含むインスタンス変数を生成し、
viewに代入しました。

2021-02-02 07:01 UTC, yupimaru reviewed
レビュー依頼ありがとうございます。
修正点確認させて頂きました。

今回の修正をもって**LGTM**とさせていただきます。
マイページのマークアップお疲れさまでした。
masterブランチへマージ後、次の実装へ進みましょう。

引き続き実装頑張っていきましょう。応援しております！

2021-02-02 07:02 UTC, merged