商品詳細
Chestnut-07/fleamarket_sample_kagawa-b pull request #5
Opened 2021-01-23 09:28 UTC by mappy1212

#What
商品詳細機能の実装。文字は仮置きなので、hamlとscssで実装した。

#why
商品の情報がより鮮明に見えるようにするため。

2021-01-23 10:58 UTC, Chestnut-07 commented
レビュー依頼ありがとうございます。

気になった点として、
#c0c0c0　
が多い様に見受けられるので変数にしても良いかと思います。

2021-01-23 11:25 UTC, Chestnut-07 reviewed
すみません。一括で送信できる方法があったのを知りませんでした。
次からは一括で送ります。
後、可能であれば、該当マークアップページのスクリーンショットを添付してもらえると助かります。

2021-01-23 11:25 UTC, Chestnut-07 commented on app/assets/stylesheets/modules/_items.scss
> +        background-color: #33cc99
セミコロンを忘れています。

2021-01-23 11:25 UTC, Chestnut-07 commented on app/assets/stylesheets/modules/_items.scss
> +          }
ここだけではないですが、同じ記述が複数箇所見られ他ので、クラスを一つにまとめて、１回で記載する形の方が良いかと思います。

2021-01-24 04:36 UTC, mappy1212 commented on app/assets/stylesheets/modules/_items.scss
> +          }
レビューありがとうございます。一旦修正してみました。

2021-01-24 04:36 UTC, mappy1212 commented on app/assets/stylesheets/modules/_items.scss
> +        background-color: #33cc99
レビューありがとうございます。修正しました。

2021-01-24 07:01 UTC, yupimaru requested changes
レビュー依頼ありがとうございます。
コメントしておりますので、ご確認のほどよろしくお願いいたします。

また、修正後再度提出される際には、現在ブラウザ上でどのように表示されているのか確認させて頂きたいため、Gyazoを用いてスクリーンショットを撮影して頂き、生成されたURLを併せてご提出下さい。

2021-01-24 07:01 UTC, yupimaru commented on app/assets/stylesheets/modules/_items_show.scss
> +      border-top: 1px solid  #c0c0c0;
```SCSS
 #c0c0c0
```

上記の色コードは繰り返し使用しているようですので、変数化して使用しましょう。

2021-01-24 07:44 UTC, mappy1212 commented on app/assets/stylesheets/modules/_items_show.scss
> +      border-top: 1px solid  #c0c0c0;
レビューありがとうございます。変数にすることができました。

2021-01-24 08:30 UTC, yupimaru reviewed
レビュー依頼ありがとうございます。
修正点確認させて頂きました。

今回の修正を持って、**LGTM**とさせて頂きます。
商品詳細ページのマークアップお疲れさまでした！

masterブランチへマージ後、次の実装へ進みましょう。
引き続き、実装頑張っていきましょう。応援しております！

2021-01-24 08:32 UTC, merged