{WIP}新規登録
Chestnut-07/fleamarket_sample_kagawa-b pull request #7
Opened 2021-01-24 08:46 UTC by yamakyou

##WHAT
新規登録画面の実装

##WHY
必須画面の為

2021-01-25 13:39 UTC, Chestnut-07 reviewed
レビュー依頼ありがとうございます。
気になった点をレビューしました。
また、レビュー依頼をするタイミングになりましたら、プルリクエストのタイトルにあるwipを消してもらえると助かります。

2021-01-25 13:39 UTC, Chestnut-07 commented on app/views/devise/registrations/new.html.haml
> +          %input.name-form{:placeholder => "例:ほげほげ", :size => "30", :type => "text"}/
ここを一例としてレビューします。（同様の箇所が他にもあります）
ハッシュロケット記法は古い記法らしいので、シンボル型に変更しても良いかと思います。

2021-01-26 07:12 UTC, yamakyou commented on app/views/devise/registrations/new.html.haml
> +          %input.name-form{:placeholder => "例:ほげほげ", :size => "30", :type => "text"}/
変更しました。

2021-01-26 07:48 UTC, Chestnut-07 reviewed
LGTMです。

2021-01-27 04:55 UTC, goku-naoki reviewed
レビュー依頼ありがとうございます！
SCSSの書き方に関してコメントをしましたので、ご確認お願いいたします！

2021-01-27 04:55 UTC, goku-naoki commented on app/assets/stylesheets/new.scss
> +// Place all the styles related to the users controller here.
scssをネストした形で記述しましょう。
&は使用しなくても大丈夫なので、chat-spaceのscssを参考にしてみて下さい。

2021-01-27 14:55 UTC, yamakyou commented on app/assets/stylesheets/new.scss
> +// Place all the styles related to the users controller here.
変更しました。

2021-01-28 04:08 UTC, yupimaru requested changes
レビュー依頼ありがとうございます。
修正点確認させて頂きました。

追加でコメントしておりますので、ご確認のほどよろしくお願いいたします。

2021-01-28 04:08 UTC, yupimaru commented on app/assets/stylesheets/new.scss
> +    background-color: #EA352D;
```SCSS
#EA352D
```

上記色コードは繰り返し使用しているようですので、変数化して使用しましょう。

2021-01-28 04:08 UTC, yupimaru commented on app/views/devise/registrations/new.html.haml
> +              %option{ value: "31"} 31
誕生日を選択する部分は一つ一つoptionで記載せずとも、1行で済ませる記述方法があります。
[こちら](https://railsdoc.com/page/date_select)を参考に書いてみましょう。

2021-01-31 06:08 UTC, yamakyou commented on app/assets/stylesheets/new.scss
> +    background-color: #EA352D;
変数化しました。

2021-01-31 06:08 UTC, yamakyou commented on app/views/devise/registrations/new.html.haml
> +              %option{ value: "31"} 31
変更しました。

2021-01-31 06:13 UTC, goku-naoki commented
修正ありがとうございます！
コード自体は問題ないので、viewファイルなどの不要なコメントアウトは全て消しましょう。

2021-01-31 06:18 UTC, goku-naoki commented
修正ありがとうございます！
LGTMとさせて頂きます！

お疲れ様です！

2021-01-31 06:19 UTC, merged