[WIP]Add items show server side
Chestnut-07/fleamarket_sample_kagawa-b pull request #8
Opened 2021-01-26 11:03 UTC by Chestnut-07

##what
商品詳細ページのサーバーサイドを実装する。
先に行ったDB設計に則り、DBを策定し、値が持って来られるかを確認する。
gemに、devise,ancestry,activehashを使用する。
出品者のみ、該当ページから編集できる様リンクが表示される様にする。
出品者以外は、購入ページに繋がる様リンクが表示される様にする。
##why
必須機能であるため。

2021-02-03 08:59 UTC, Chestnut-07 commented
view:商品詳細ページ　
![item_show view](https://user-images.githubusercontent.com/75065421/106722405-4323d680-6649-11eb-8bb1-45b954cd68c1.png)

2021-02-03 09:41 UTC, bonkura-bird reviewed
レビュー依頼ありがとうございます。
気になった点にコメントしましたので確認お願いします

2021-02-03 09:41 UTC, bonkura-bird commented on app/models/user.rb
> +
実際のフリマアプリでも名前被りできますし、nicknameに一意制約をつける必要は特にないかと思います。どちらかというと、emailの一意制約をDB側、モデル側から二重にかけることで、一意制約をより強固にできるのではないかと思います

2021-02-03 09:41 UTC, bonkura-bird commented on app/views/items/new.html.haml
> +          -# = f.select :preparation_day, [['1〜2日で発送', "1_2days"], ['2〜3日で発送', "2_3days"], ['4〜7日で発送', "4_7days"]], { include_blank: '--選択してください--'}, { id: "delivary_days", id: "preparation_day", req
ここのコメントアウトは必要なのでしょうか？

2021-02-03 09:41 UTC, bonkura-bird commented on db/migrate/20210129063007_create_destinations.rb
> +      t.references :user, null: false, foreign_key: true
`@hone_number`
カラム名はこれでいいのでしょうか？

2021-02-03 09:41 UTC, bonkura-bird commented on db/schema.rb
> +    t.bigint "user_id", null: false
`@hone_number`
カラム名はこれでいいのでしょうか？

2021-02-04 09:01 UTC, Chestnut-07 commented on app/views/items/new.html.haml
> +          -# = f.select :preparation_day, [['1〜2日で発送', "1_2days"], ['2〜3日で発送', "2_3days"], ['4〜7日で発送', "4_7days"]], { include_blank: '--選択してください--'}, { id: "delivary_days", id: "preparation_day", req
コメントアウトを削除しました。

2021-02-04 09:01 UTC, Chestnut-07 commented on app/models/user.rb
> +
nicknameの一意制約を辞めました。

2021-02-04 09:02 UTC, Chestnut-07 commented on db/migrate/20210129063007_create_destinations.rb
> +      t.references :user, null: false, foreign_key: true
カラム名を変更するmigrationファイルを作成し、カラム名をphone_numberに変更しました。

2021-02-04 09:03 UTC, Chestnut-07 commented on db/schema.rb
> +    t.bigint "user_id", null: false
カラム名を変更するmigrationファイルを作成し、カラム名をphone_numberに変更しました。

2021-02-04 09:08 UTC, bonkura-bird commented
お疲れさまです。
LGTMです。

2021-02-04 09:44 UTC, yupimaru requested changes
レビュー依頼ありがとうございます。
コメントしておりますので、ご確認のほどよろしくお願いいたします。

また、添付いただきましたスクリーンショット画像を確認させて頂きましたが、
商品画像が動物の写真であるように見受けられました。
いくらテストデータであるとはいえ、**一般的にフリマサイトに出品されるべきではないものを出品することは控えましょう。**

2021-02-04 09:44 UTC, yupimaru commented on app/views/items/show.html.haml
>              衣類
```haml
衣類
```

こちらですが、カテゴリーの値だけ仮置きのままになっているようです。
データベースに保存されている値を取り出す実装は、別途実装されますか？

2021-02-04 09:44 UTC, yupimaru commented on app/views/items/show.html.haml
>            発送元の地域
**53行目**
```haml
ゆうパック
```

こちら、配送の方法が仮置きデータのままになっているように見受けられます。
データベースに保存されている情報が表示できるように修正しましょう。

2021-02-04 09:44 UTC, yupimaru commented on test/fixtures/categories.yml
> +# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
**test/fixtures/categories.yml**

こちらのファイルは、今回の実装では使用しないかと思われますので、
ファイルごと削除しておきましょう。

2021-02-04 09:44 UTC, yupimaru commented on test/fixtures/conditions.yml
> +# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
**test/fixtures/conditions.yml**

こちらのファイルは、今回の実装では使用しないか思われますので、
ファイルごと削除しておきましょう。

2021-02-04 09:44 UTC, yupimaru commented on test/fixtures/destinations.yml
> +# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
**test/fixtures/destinations.yml**

こちらのファイルは、今回の実装では使用しないかと思われますので、
ファイルごと削除しておきましょう。

2021-02-04 09:44 UTC, yupimaru commented on test/fixtures/item_images.yml
> +# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
**test/fixtures/item_images.yml**

こちらのファイルは、今回の実装では使用しないか思われますので、
ファイルごと削除しておきましょう。

2021-02-04 09:44 UTC, yupimaru commented on test/fixtures/items.yml
> +# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
**test/fixtures/items.yml**

こちらのファイルは、今回の実装では使用しないか思われますので、
ファイルごと削除しておきましょう。

2021-02-04 09:44 UTC, yupimaru commented on test/fixtures/prefectures.yml
> +# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
**test/fixtures/prefectures.yml**

こちらのファイルは、今回の実装では使用しないか思われますので、
ファイルごと削除しておきましょう。

2021-02-04 09:44 UTC, yupimaru commented on test/fixtures/preparation_days.yml
> +# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
**test/fixtures/preparation_days.yml**

こちらのファイルは、今回の実装では使用しないか思われますので、
ファイルごと削除しておきましょう。

2021-02-04 09:44 UTC, yupimaru commented on test/fixtures/shipping_fee_payers.yml
> +# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
**test/fixtures/shipping_fee_payers.yml**

こちらのファイルは、今回の実装では使用しないか思われますので、
ファイルごと削除しておきましょう。

2021-02-04 09:44 UTC, yupimaru commented on test/models/category_test.rb
> +require 'test_helper'
**test/models/category_test.rb**

こちらのファイルは、今回の実装では使用しないか思われますので、
ファイルごと削除しておきましょう。

2021-02-04 09:44 UTC, yupimaru commented on test/models/condition_test.rb
> +require 'test_helper'
**test/models/condition_test.rb**

こちらのファイルは、今回の実装では使用しないか思われますので、
ファイルごと削除しておきましょう。

2021-02-04 09:44 UTC, yupimaru commented on test/models/destination_test.rb
> +require 'test_helper'
**test/models/destination_test.rb**

こちらのファイルは、今回の実装では使用しないか思われますので、
ファイルごと削除しておきましょう。

2021-02-04 09:44 UTC, yupimaru commented on test/models/item_image_test.rb
> +require 'test_helper'
**test/models/item_image_test.rb**

こちらのファイルは、今回の実装では使用しないか思われますので、
ファイルごと削除しておきましょう。

2021-02-04 09:44 UTC, yupimaru commented on test/models/item_test.rb
> +require 'test_helper'
**test/models/item_test.rb**

こちらのファイルは、今回の実装では使用しないか思われますので、
ファイルごと削除しておきましょう。

2021-02-04 09:44 UTC, yupimaru commented on test/models/prefecture_test.rb
> +require 'test_helper'
**test/models/prefecture_test.rb**

こちらのファイルは、今回の実装では使用しないか思われますので、
ファイルごと削除しておきましょう。

2021-02-04 09:44 UTC, yupimaru commented on test/models/preparation_day_test.rb
> +require 'test_helper'
**test/models/preparation_day_test.rb**

こちらのファイルは、今回の実装では使用しないか思われますので、
ファイルごと削除しておきましょう。

2021-02-04 09:44 UTC, yupimaru commented on test/models/shipping_fee_payer_test.rb
> +require 'test_helper'
**test/models/shipping_fee_payer_test.rb**

こちらのファイルは、今回の実装では使用しないか思われますので、
ファイルごと削除しておきましょう。

2021-02-04 09:44 UTC, yupimaru commented on app/views/items/new.html.haml
> +          %label{for: "preparation"}
```haml
%label{for: "preparation"}
```

上記の記述ですが、6行目で`form_with`を用いているようですので、
`label`タグを直接記述するのではなく、`f.~`の形で記述しましょう。

2021-02-04 09:44 UTC, yupimaru commented on app/views/items/new.html.haml
> +          = f.collection_select(:item_prefecture_id, Prefecture.all, :id, :name, { include_blank: "--選択してください--" }, { id: "prefecture", required: "required"})
**77行目**
```haml
%label{for: "prefecture"}
```

上記の記述ですが、6行目で`form_with`を用いているようですので、
`label`タグを直接記述するのではなく、`f.~`の形で記述しましょう。

2021-02-04 09:44 UTC, yupimaru commented on app/views/items/new.html.haml
>              配送料の負担
**71行目**
```haml
%label{for: "shipping"}
```

上記の記述ですが、6行目で`form_with`を用いているようですので、
`label`タグを直接記述するのではなく、`f.~`の形で記述しましょう。

2021-02-04 09:44 UTC, yupimaru commented on app/views/items/new.html.haml
>              商品の状態
**47行目**
```haml
%label{for: "categories"}
```

**53行目**
```haml
%label{for: "status"}
```

**59行目**
```haml
%label{for: "condition"}
```

上記の記述ですが、6行目で`form_with`を用いているようですので、
`label`タグを直接記述するのではなく、`f.~`の形で記述しましょう。

2021-02-04 09:44 UTC, yupimaru commented on app/views/items/new.html.haml
>              商品の説明
**32行目**
```haml
%label{for: "item_introduction"}
```

上記の記述ですが、6行目で`form_with`を用いているようですので、
`label`タグを直接記述するのではなく、`f.~`の形で記述しましょう。

2021-02-05 06:04 UTC, Chestnut-07 commented on app/views/items/show.html.haml
>              衣類
別途実装します。

2021-02-05 07:04 UTC, Chestnut-07 commented on app/views/items/show.html.haml
>            発送元の地域
追加しました。

2021-02-05 07:04 UTC, Chestnut-07 commented on test/fixtures/categories.yml
> +# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
削除しました。

2021-02-05 07:04 UTC, Chestnut-07 commented on test/fixtures/conditions.yml
> +# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
削除しました。

2021-02-05 07:04 UTC, Chestnut-07 commented on test/fixtures/destinations.yml
> +# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
削除しました。

2021-02-05 07:04 UTC, Chestnut-07 commented on test/fixtures/item_images.yml
> +# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
削除しました。

2021-02-05 07:05 UTC, Chestnut-07 commented on test/fixtures/items.yml
> +# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
削除しました。

2021-02-05 07:05 UTC, Chestnut-07 commented on test/fixtures/prefectures.yml
> +# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
削除しました。

2021-02-05 07:05 UTC, Chestnut-07 commented on test/fixtures/preparation_days.yml
> +# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
削除しました。

2021-02-05 07:05 UTC, Chestnut-07 commented on test/fixtures/shipping_fee_payers.yml
> +# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
削除しました。

2021-02-05 07:05 UTC, Chestnut-07 commented on test/models/category_test.rb
> +require 'test_helper'
削除しました。

2021-02-05 07:05 UTC, Chestnut-07 commented on test/models/condition_test.rb
> +require 'test_helper'
削除しました。

2021-02-05 07:05 UTC, Chestnut-07 commented on test/models/destination_test.rb
> +require 'test_helper'
削除しました。

2021-02-05 07:05 UTC, Chestnut-07 commented on test/models/item_image_test.rb
> +require 'test_helper'
削除しました。

2021-02-05 07:05 UTC, Chestnut-07 commented on test/models/item_test.rb
> +require 'test_helper'
削除しました。

2021-02-05 07:06 UTC, Chestnut-07 commented on test/models/prefecture_test.rb
> +require 'test_helper'
削除しました。

2021-02-05 07:06 UTC, Chestnut-07 commented on test/models/preparation_day_test.rb
> +require 'test_helper'
削除しました。

2021-02-05 07:06 UTC, Chestnut-07 commented on test/models/shipping_fee_payer_test.rb
> +require 'test_helper'
削除しました。

2021-02-05 07:33 UTC, Chestnut-07 commented on app/views/items/new.html.haml
> +          %label{for: "preparation"}
記述を変更しました。

2021-02-05 07:33 UTC, Chestnut-07 commented on app/views/items/new.html.haml
> +          = f.collection_select(:item_prefecture_id, Prefecture.all, :id, :name, { include_blank: "--選択してください--" }, { id: "prefecture", required: "required"})
記述を変更しました。

2021-02-05 07:33 UTC, Chestnut-07 commented on app/views/items/new.html.haml
>              配送料の負担
記述を変更しました。

2021-02-05 07:33 UTC, Chestnut-07 commented on app/views/items/new.html.haml
>              商品の状態
記述を変更しました。

2021-02-05 07:33 UTC, Chestnut-07 commented on app/views/items/new.html.haml
>              商品の説明
記述を変更しました。

2021-02-05 08:53 UTC, goku-naoki commented
レビュー依頼ありがとうございます！
コメント箇所の修正を確認できましたのでLGTMとさせて頂きます！
実装お疲れ様でした！

2021-02-05 09:41 UTC, merged